version: "3.9"
services: 
    api:
        build: .
        container_name: api
        ports:
          - "8080:5000"
        depends_on:
          - db

    db:
        image: "mcr.microsoft.com/mssql/server:2022-latest"
        ports:
          - "1433:1433"

        environment:
            SA_PASSWORD: "yasin@2001"
            ACCEPT_EULA: "Y"